services:
  caddy:
    image: caddy:latest
    container_name: csp_caddy
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    depends_on:
      - csp-receiver
    networks:
      - csp-net

  csp-receiver:
    build:
      context: ./csp-receiver-app
    container_name: csp_receiver
    expose:
      - "5000"
    volumes:
      - ./csp-receiver-app:/app
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - REPORTING_SECRET_TOKEN=${REPORTING_SECRET_TOKEN}
      - RABBITMQ_NODES_CSV=${RABBITMQ_NODES_CSV:-rabbitmq1:5672,rabbitmq2:5672,rabbitmq3:5672}
      - RABBITMQ_USER=${RABBITMQ_USER:-user}
      - RABBITMQ_PASS=${RABBITMQ_PASS:-password}
      - QUEUE_NAME=${QUEUE_NAME:-csp_reports_queue}
      - RABBITMQ_CONNECTION_ATTEMPTS_PER_NODE=${RABBITMQ_CONNECTION_ATTEMPTS_PER_NODE:-3}
      - RABBITMQ_RETRY_DELAY_PER_NODE=${RABBITMQ_RETRY_DELAY_PER_NODE:-5}
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    networks:
      - csp-net
    restart: unless-stopped

  rabbitmq1:
    image: rabbitmq:4.0-management-alpine
    container_name: csp_rabbitmq1
    hostname: rabbitmq1
    ports:
      - "15672:15672" # Management UI for node 1
    volumes:
      - rabbitmq1_data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-user}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-password}
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-SUPER_SECRET_COOKIE_VALUE_CHANGE_ME}
    networks:
      - csp-net
    restart: unless-stopped

  rabbitmq2:
    image: rabbitmq:4.0-management-alpine
    container_name: csp_rabbitmq2
    hostname: rabbitmq2
    volumes:
      - rabbitmq2_data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-user}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-password}
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-SUPER_SECRET_COOKIE_VALUE_CHANGE_ME}
    depends_on:
      - rabbitmq1
    networks:
      - csp-net
    restart: unless-stopped

  rabbitmq3:
    image: rabbitmq:4.0-management-alpine
    container_name: csp_rabbitmq3
    hostname: rabbitmq3
    volumes:
      - rabbitmq3_data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-user}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-password}
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-SUPER_SECRET_COOKIE_VALUE_CHANGE_ME}
    depends_on:
      - rabbitmq1
    networks:
      - csp-net
    restart: unless-stopped

  csp-worker:
    build:
      context: ./csp-worker-app
    container_name: csp_worker
    volumes:
      - ./csp-worker-app:/app
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - RABBITMQ_NODES_CSV=${RABBITMQ_NODES_CSV:-rabbitmq1:5672,rabbitmq2:5672,rabbitmq3:5672}
      - RABBITMQ_USER=${RABBITMQ_USER:-user}
      - RABBITMQ_PASS=${RABBITMQ_PASS:-password}
      - QUEUE_NAME=${QUEUE_NAME:-csp_reports_queue}
      - RABBITMQ_RETRY_DELAY=${RABBITMQ_RETRY_DELAY:-10}
      - RABBITMQ_CONNECTION_ATTEMPTS_PER_NODE=${RABBITMQ_CONNECTION_ATTEMPTS_PER_NODE:-3}
      - RABBITMQ_RETRY_DELAY_PER_NODE=${RABBITMQ_RETRY_DELAY_PER_NODE:-5}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS:-http://elasticsearch:9200}
      - ELASTICSEARCH_INDEX_PREFIX=${ELASTICSEARCH_INDEX_PREFIX:-csp-violations}
      - ES_CONNECTION_RETRIES=${ES_CONNECTION_RETRIES:-5}
      - ES_RETRY_DELAY=${ES_RETRY_DELAY:-10}
      - BULK_MAX_SIZE=${BULK_MAX_SIZE:-100}
      - BULK_MAX_SECONDS_FLUSH=${BULK_MAX_SECONDS_FLUSH:-10}
      - PROCESS_DATA_EVENTS_TIMEOUT=${PROCESS_DATA_EVENTS_TIMEOUT:-1.0}
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
      - elasticsearch
    networks:
      - csp-net
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:9.1.2
    container_name: csp_elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile: { soft: 65536, hard: 65536 }
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - csp-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s || exit 1"] # Adjusted healthcheck
      interval: 10s
      timeout: 10s # Increased timeout for healthcheck
      retries: 10

  kibana:
    image: kibana:9.1.2
    container_name: csp_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - csp-net
    restart: unless-stopped

  volumes:
  caddy_data:
  rabbitmq1_data:
  rabbitmq2_data:
  rabbitmq3_data:
  es_data:

networks:
  csp-net:
    driver: bridge
